### ISSUE TITLE
ID 17: Reusability Indicator

### ISSUE THREAD

**Issue by Maximilian-Stefan-Ernst** [brandmaier/research_software_evaluation#8]
This is on of the two only criteria used in the phase 1 algorithm. It is therefore central. However, it is also problematic, as it conflates several aspects and the formulation is unclear. For example, 

> R2 (2 points): Well-developed and tested software, fairly extensive documentation, ...

> R3 (4 points): ...extensive documentation, systematic bug chasing and unit testing, ...
 
Well-tested implied unit tests? What is the difference between "fairly extensive" and "extensive" documentation?

Why not instead make it like this:

- Open Source: 1 point
- Unit Tests: 1 point
- Documentation:
  - docstrings: .5 points
  - tutorials: .5 points
- CI: 1 point
- changelogs with bug reports: 1 point
- possibility to report bugs and ask questions: 1 point (This is central. Consider for example the tons of questions answered on the lavaan mailing list - thats a lot of work.)

**Comment by brandmaier** [comment]
very good!

**Comment by brandmaier** [comment]
currently, there is a mismatch between rigor in manuscript and software. Rigor first, impact second.

**Comment by brandmaier** [comment]
I propose to deduce points if software is not open source. I think penalizing closed source instead of allowing fewer points makes a stronger case against closed source. Otherwise, we now suggest that some of these aspects are individual indicators: https://github.com/brandmaier/research_software_evaluation/pull/14
however, I don't think having changelogs should be equated with unit tests and documentation, so I removed it.
See https://github.com/brandmaier/research_software_evaluation/pull/14
